### ISSUE TITLE
java.time.LocalDate causes MappingException

### ISSUE THREAD

**Issue by daesul** [bguerout/jongo#236]
Finding a LocalDate cases this exception:
Exception in thread "main" org.jongo.marshall.MarshallingException: Unable to unmarshall result to class java.time.LocalDate from content { "_id" : { "$oid" : "54ae7860bfde09c23ddfd889"} , "year" : 1980 , "month" : 1 , "day" : 1 , "leapYear" : true}
	at org.jongo.marshall.jackson.JacksonEngine.unmarshall(JacksonEngine.java:45)
	at org.jongo.ResultHandlerFactory$UnmarshallingResultHandler.map(ResultHandlerFactory.java:43)
	at org.jongo.FindOne.map(FindOne.java:51)
	at org.jongo.FindOne.as(FindOne.java:46)
	at de.codecentric.hellojongo.SimpleExample.main(SimpleExample.java:45)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class java.time.LocalDate]: can not instantiate from JSON object (need to add/enable type information?)
 at [Source: de.undercouch.bson4jackson.io.LittleEndianInputStream@40e6dfe1; pos: 0]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1065)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:268)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:124)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1269)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:928)
	at org.jongo.marshall.jackson.JacksonEngine.unmarshall(JacksonEngine.java:42)
	... 4 more

Finding a single LocalDate or an embedded LocalDate results to the same Exception.

Raising jackson to higher version may solve the problem.

**Comment by bguerout** [comment]
You probably need to add JodaModule.
Here is more informations : https://github.com/bguerout/jongo/issues/229

**Comment by bguerout** [comment]
Please reopen if you need more informations

**Comment by mpages** [comment]
you need to add mapper to support new java 8 type:
https://github.com/FasterXML/jackson-datatype-jsr310
https://github.com/FasterXML/jackson-datatype-jdk8

```
Builder tmpMapper = new JacksonMapper.Builder();
		for (Module module : ObjectMapper.findModules()) {
			tmpMapper.registerModule(module);
		}
		tmpMapper.enable(MapperFeature.AUTO_DETECT_GETTERS);
		tmpMapper.registerModule(new JSR310Module()).registerModule(new Jdk8Module());

		jongo = new Jongo(database, tmpMapper.build());
```

**Comment by bguerout** [comment]
Cool thanks.
