### ISSUE TITLE
All positional operator `$[]` throws `JsonParseException` in 1.5.0

### ISSUE THREAD

**Issue by hisener** [bguerout/jongo#386]
After upgrading Jongo 1.5.0, we started seeing `JsonParseException` in a couple of places where we use all positional operator `$[]`. Our usages are the same as the example in [MongoDB doc](https://docs.mongodb.com/manual/reference/operator/update/positional-all/#update-all-documents-in-an-array).

`BsonQueryFactory#addRequiredQuotesAndParameters` seems like the culprit as it applies the following transformations, and therefore `BasicDBObject.parse` fails:

```
{ $set: { array.$[].id: 10 } } -> {"$set":{[  array.$]".id": 10 } }
```

My test case in `BsonQueryFactoryTest`:

```java
@Test
public void allPositionalOperator() {
    assertThatCode(() -> factory.createQuery("{ $set: { array.$[].id: 10 } }")).doesNotThrowAnyException();
}
```

Failure:

```
java.lang.AssertionError: 
Expecting code not to raise a throwable but caught
  "java.lang.IllegalArgumentException: Cannot parse query: { $set: { array.$[].id: 10 } }
	at org.jongo.query.BsonQueryFactory.createQuery(BsonQueryFactory.java:106)
	at org.jongo.query.BsonQueryFactoryTest.lambda$allPositionalOperator$0(BsonQueryFactoryTest.java:390)
...
Caused by: org.bson.json.JsonParseException: JSON reader was expecting a name but found '['.
	at org.bson.json.JsonReader.readBsonType(JsonReader.java:146)
	at com.mongodb.DBObjectCodec.readDocument(DBObjectCodec.java:397)
	at com.mongodb.DBObjectCodec.readValue(DBObjectCodec.java:322)
	at com.mongodb.DBObjectCodec.readDocument(DBObjectCodec.java:399)
	at com.mongodb.DBObjectCodec.decode(DBObjectCodec.java:167)
	at com.mongodb.DBObjectCodec.decode(DBObjectCodec.java:67)
	at com.mongodb.BasicDBObject.parse(BasicDBObject.java:83)
	at com.mongodb.BasicDBObject.parse(BasicDBObject.java:70)
	at org.jongo.query.BsonQueryFactory.createQuery(BsonQueryFactory.java:99)
```

Also, Jongo 1.4.1 returns the expected query:

```
{"$set": {"array.$[].id": 10}}
```

**Comment by Dayde** [comment]
You can add quotes around your key, the following test runs as expected

```
@Test
public void allPositionalOperator() {
    assertThatCode(() -> factory.createQuery("{ $set: { 'array.$[].id': 10 } }")).doesNotThrowAnyException();
}
```

I’ve been trying to modify the query builder to accept the query without the quotes but it is quite tricky to do so without introducing a lot of complexity to the algorithm. Considering the doc you mentioned had those quotes I’m not sure we want to fix it.

**Comment by hisener** [comment]
Thanks @Dayde. It's still surprising this works in Jongo 1.4.1, though. 🙂

**Comment by Dayde** [comment]
Not really to me as the query factory was rewritten from scratch while updating to mongo legacy driver 4.x
